Repository johnktravers/globe_trotter_api, pull requests merged in 2020-02, with the labels that each got.

#1 Create sprint 1 tables and migrations
  trips/migrations/0001_initial.py
  trips/models.py
Labels: Backend, Database, Sprint 1

#4 User can see a list of saved trips
  trips/schema.py
  trips/tests.py
Labels: Backend, Sprint 1, Trips View

#3 Setup Travis CI and Heroku Deployment
  .travis.yml
  Pipfile
  Pipfile.lock
  globe_trotter/settings.py
Labels: Backend, Deployment, Sprint 1

#5 Setup Travis CI and Heroku Deployment
  Procfile
Labels: Backend, Deployment, Sprint 1

#8 Configure application CORS
  Pipfile
  Pipfile.lock
  globe_trotter/settings.py
Labels: Backend

#11 User can create a destination for a trip
  trips/schema.py
  trips/tests.py
Labels: Backend, Sprint 2

#12 User can get a list of Yelp activities for a location
  globe_trotter/urls.py
  trips/admin.py
  trips/views.py
  yelp_activities/__init__.py
  yelp_activities/apps.py
  yelp_activities/tests.py
  yelp_activities/views.py
Labels: Backend, Sprint 2

#13 Add documentation for GraphQL endpoint
  README.md
Labels: Backend, GraphQL

#14 Invalid location error handling for trip and destination creation
  trips/schema.py
  trips/tests.py
Labels: Backend, GraphQL, Sprint 2

#15 User can add an activity to a trip destination #42
  trips/schema.py
  trips/tests.py
Labels: Backend, GraphQL, Sprint 2

#16 User can delete a trip
  README.md
  trips/schema.py
  trips/tests.py
Labels: Backend, GraphQL, Sprint 2

#17 User can delete an activity
  README.md
  trips/schema.py
  trips/tests.py
Labels: Backend, GraphQL, Sprint 2

#19 Travis CI README badge
  README.md
Labels: Backend

#21 Lat/long sad path for yelp_activities endpoint
  trips/schema.py
  yelp_activities/tests.py
  yelp_activities/views.py
Labels: Backend, RESTful, Sprint 3
